### PR TITLE
Fix rhel8 mockbuilds for rhel8.1 modules error.

### LINKED ISSUE #228: rhel8 mock builds are broken because of rhel8.1 release
Fix mock building for rhel8
It is currently pulling in 8.1 rpms in conjunction with 8.0 rpms
```
No available modular metadata for modular package 'python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64', it cannot be installed on the system
No available modular metadata for modular package 'python36-devel-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64', it cannot be installed on the system
Error: No available modular metadata for modular package
```

However, scratch builds are still working properly.

### PR DESCRIPTION
**Pull request by myersCody**
Closes #228

### CODE REVIEW

**Comment by kholdaway** [comment]
Did rhpkg go away?

**Comment by myersCody** [comment]
> Let’s put `discovery-0.9-rhel-8-build` in a variable at the top of the makefile.

Hmm. I think from my point of view it will be a find and replace either way, but I can add the var to all 26 files.

**Comment by myersCody** [comment]
> Did rhpkg go away?

So, you can grab the mock config using two separate commands either through the rhpkg cli or through the brew cli. I think for this instance the brew cli was better because it pulled it from the same area the scratch builds are configured. Which does contain the hot fixes that the rcm put out there for instances like this.

**Comment by kholdaway** [comment]
> > Let’s put `discovery-0.9-rhel-8-build` in a variable at the top of the makefile.
> 
> Hmm. I think from my point of view it will be a find and replace either way, but I can add the var to all the files.

In general, it's a cleaner coding style to add constants for values you expect to change.  Given the value, I would expect this to change with releases.

**Pull request merged**
